#!/usr/bin/env python3
import argparse
import glob

try:
    from bs4 import BeautifulSoup as bs

    print("Beautiful Soup found, will prettyify too")
except ModuleNotFoundError:
    print("Beautiful Soup not found, lets get fugly")
    bs = None

cdn = '<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>'

starttag = "<script"
endtag = "</script>"

def shrink_text(text):
    lastpos = 0

    # Find the start/end tags of the plotly js dump
    while True:
        start = text.find(starttag, lastpos)

        if start == -1:
            break

        end = text.find(endtag, start) + len(endtag)

        lastpos = end

        if "plotly.js" in text[start:end]:
            print("\toverwriting", filename)
            # Found the offending script. delete it and replace with the CDN
            text = text[:start] + cdn + text[end:]

            text = beautify(text)
            return text
    print("\tnothing to do", filename)
    return None

def shrink_file(filename):
    with open(filename) as f:
        text = f.read()

    text = shrink_text(text)

    if text:
        # Rewrite the file
        with open(filename, "w") as f:
            f.write(text)



def beautify(html):
    if bs is None:
        return html
    soup = bs(html, "lxml")
    return soup.prettify()


if __name__ == "__main__":
    finder = glob.glob("*.htm*")
    print(finder)

    for filename in finder:
        print(filename)
        print("Changing ", filename)
        shrink_file(filename)
