#!/usr/bin/env python3
import argparse
import glob

try:
    from bs4 import BeautifulSoup as bs

    print("Beautiful Soup found, will prettyify too")
except ModuleNotFoundError:
    print("Beautiful Soup not found, lets get fugly")
    bs = None

cdn = '<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>'

starttag = "<script"
endtag = "</script>"


def shrink_file(filename):
    with open(filename) as f:
        data = f.read()

    lastpos = 0

    # Find the start/end tags of the plotly js dump
    while True:
        start = data.find(starttag, lastpos)

        if start == -1:
            break

        end = data.find(endtag, start) + len(endtag)

        lastpos = end

        if "plotly.js" in data[start:end]:
            print("\toverwriting", filename)
            # Found the offending script. delete it and replace with the CDN
            data = data[:start] + cdn + data[end:]

            data = beautify(data)

            # Rewrite the file
            with open(filename, "w") as f:
                f.write(data)
            return

    print("\tnothing to do", filename)


def beautify(html):
    if bs is None:
        return html
    soup = bs(html, "lxml")
    return soup.prettify()


if __name__ == "__main__":
    finder = glob.glob("*.htm*")
    print(finder)

    for filename in finder:
        print(filename)
        print("Changing ", filename)
        shrink_file(filename)
