#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname $0)"/..

# Do OS install first
sh -c "os/install"

# find the installers and run them iteratively
find . -name install.sh | while read installer ; do echo "${installer}" ;  sh -c "${installer}" ; done

sh -c "setup/bootstrap"

sudo chsh $USER -s /bin/zsh

zsh
